In [3]:
import numpy as np

In [19]:
def nonlin(x,deriv=False):
    if deriv:
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [20]:
#1 layer neural network
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,0,1,1]]).T

print("X:",X)
print("y:",y)

np.random.seed(1)
syn0 = 2*np.random.random((3,1))-1

for j in range(10000):
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    
    l1_error = y-l1
    
    l1_delta = l1_error*nonlin(l1,True)
    
    syn0 += np.dot(l0.T,l1_delta)
    #print("iter:",j," ","l1_error:",l1_error)
print("output:",l1)

X: [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
y: [[0]
 [0]
 [1]
 [1]]
output: [[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]


In [25]:
#3 layer neural network
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])

y = np.array([[0],
             [1],
             [1],
             [0]]) 

np.random.seed(1)

#initialize weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in range(60000):
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    
    l2_error = y-l2
    
    if(j%10000) ==0:
        print("Error:" + str(np.mean(np.abs(l2_error))))
        
    l2_delta = l2_error * nonlin(l2,deriv=True)
    
    l1_error = l2_delta.dot(syn1.T)
    l1_delta = l1_error*nonlin(l1,deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
print("Output:",l2)

Error:0.49641003190272537
Error:0.008584525653247155
Error:0.005789459862507806
Error:0.004629176776769984
Error:0.003958765280273648
Error:0.003510122567861677
Output: [[0.00260572]
 [0.99672209]
 [0.99701711]
 [0.00386759]]
